### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by truerishab** [thecyberworld/support#26]
### Name

Rishab gupta

### Discord Username (if applicable)

rishab#0202

### Additional Context

I want to join this organization because i find this role really interesting & challenging too. I'm having 2 years of experience in the cyber field of work & i'm quite sure that the skills that i've acquired from my current organization & past experience will help me do this work very effectively. As i'm an experienced candidate in the similar field so i'm looking for an organization with long term commitment. i think your organization will be the best place to work, i'm sure i'll also learn & improve my skills if got a chance to work for your organization.

**Comment by 0xk4b1r** [comment]
hey @BadKarma187

**Comment by truerishab** [comment]
hi
